language: go
go:
- 1.8.x
env:
  global:
  - SSH_KEY="travis_key"
  - GIT_NAME="VigoTech Alliance"
  - GIT_EMAIL="vigotechalliance@gmail.com"
  - SOURCE_DIR="docs"
  - DEPLOY_BRANCH="source"
before_install:
- openssl aes-256-cbc -K $encrypted_35b54c54cbb7_key -iv $encrypted_35b54c54cbb7_iv -in travis_key.enc -out travis_key -d
before_script:
- git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
- go get -v github.com/spf13/hugo
- go get -v github.com/tidwall/gjson
script:
- go run scripts/vigotech.go
- hugo
after_success:
- ./scripts/deploy.sh
